language: cpp
 
before_install:
  - sudo apt-get install build-essential libboost-all-dev libcurl4-openssl-dev libdb5.1-dev libdb5.1++-dev libssl-dev libminiupnpc-dev -y

install:
 - cd src
 
script: 
 - make -f makefile.unix -j 3
 - make check
 
notifications:
  irc:
    channels:
      - "chat.freenode.net#cryptopools"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
